#define CARVE_VERSION "2.0.0a"

/* #undef HAVE_TR1_UNORDERED_COLLECTIONS */
/* #undef HAVE_STD_UNORDERED_COLLECTIONS */
/* #undef HAVE_LIBSTDCPP_UNORDERED_COLLECTIONS */
#define HAVE_BOOST_UNORDERED_COLLECTIONS

#ifndef CARVE_SYSTEM_BOOST
    #define CARVE_SYSTEM_BOOST
#endif

/* #undef CARVE_DEBUG */
/* #undef CARVE_DEBUG_WRITE_PLY_DATA */

#define CARVE_USE_EXACT_PREDICATES
